var annotated_dup =
[
    [ "CALLINFO", "struct_c_a_l_l_i_n_f_o.html", "struct_c_a_l_l_i_n_f_o" ],
    [ "IREP", "struct_i_r_e_p.html", "struct_i_r_e_p" ],
    [ "IREP_CATCH_HANDLER", "struct_i_r_e_p___c_a_t_c_h___h_a_n_d_l_e_r.html", "struct_i_r_e_p___c_a_t_c_h___h_a_n_d_l_e_r" ],
    [ "MEMORY_POOL", "struct_m_e_m_o_r_y___p_o_o_l.html", "struct_m_e_m_o_r_y___p_o_o_l" ],
    [ "MRBC_ALLOC_PROF", "struct_m_r_b_c___a_l_l_o_c___p_r_o_f.html", "struct_m_r_b_c___a_l_l_o_c___p_r_o_f" ],
    [ "MRBC_ALLOC_STATISTICS", "struct_m_r_b_c___a_l_l_o_c___s_t_a_t_i_s_t_i_c_s.html", "struct_m_r_b_c___a_l_l_o_c___s_t_a_t_i_s_t_i_c_s" ],
    [ "MRBC_DEFINE_METHOD_LIST", "struct_m_r_b_c___d_e_f_i_n_e___m_e_t_h_o_d___l_i_s_t.html", "struct_m_r_b_c___d_e_f_i_n_e___m_e_t_h_o_d___l_i_s_t" ],
    [ "RArray", "struct_r_array.html", "struct_r_array" ],
    [ "RBasic", "struct_r_basic.html", "struct_r_basic" ],
    [ "RBuiltinClass", "struct_r_builtin_class.html", "struct_r_builtin_class" ],
    [ "RBuiltinNoMethodClass", "struct_r_builtin_no_method_class.html", "struct_r_builtin_no_method_class" ],
    [ "RClass", "struct_r_class.html", "struct_r_class" ],
    [ "RException", "struct_r_exception.html", "struct_r_exception" ],
    [ "RHash", "struct_r_hash.html", "struct_r_hash" ],
    [ "RHashIterator", "struct_r_hash_iterator.html", "struct_r_hash_iterator" ],
    [ "RInstance", "struct_r_instance.html", "struct_r_instance" ],
    [ "RKeyValue", "struct_r_key_value.html", "struct_r_key_value" ],
    [ "RKeyValueHandle", "struct_r_key_value_handle.html", "struct_r_key_value_handle" ],
    [ "RKeyValueIterator", "struct_r_key_value_iterator.html", "struct_r_key_value_iterator" ],
    [ "RMethod", "struct_r_method.html", "struct_r_method" ],
    [ "RMutex", "struct_r_mutex.html", "struct_r_mutex" ],
    [ "RObject", "struct_r_object.html", "struct_r_object" ],
    [ "RPrintf", "struct_r_printf.html", "struct_r_printf" ],
    [ "RPrintfFormat", "struct_r_printf_format.html", "struct_r_printf_format" ],
    [ "RProc", "struct_r_proc.html", "struct_r_proc" ],
    [ "RRange", "struct_r_range.html", "struct_r_range" ],
    [ "RString", "struct_r_string.html", "struct_r_string" ],
    [ "RTcb", "struct_r_tcb.html", "struct_r_tcb" ],
    [ "SYM_INDEX", "struct_s_y_m___i_n_d_e_x.html", "struct_s_y_m___i_n_d_e_x" ],
    [ "tr_pattern", "structtr__pattern.html", "structtr__pattern" ],
    [ "VM", "struct_v_m.html", "struct_v_m" ]
];